"""GitHub-flavored Markdown reporting for pull requests."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any


def _get(value: object, name: str, default: Any = None) -> Any:
    if isinstance(value, Mapping):
        return value.get(name, default)
    return getattr(value, name, default)


def _text(value: object) -> str:
    return str(value).replace("\n", " ").replace("|", "\\|")


def _status(value: object) -> str:
    passed = _get(value, "passed", _get(value, "status") in {"pass", "passed"})
    return "✅ Pass" if passed else "❌ Fail"


def render_github_markdown(report: object, *, max_findings: int = 20) -> str:
    """Render a normalized report as bounded, PR-safe Markdown."""
    score = _get(report, "quality_score", _get(report, "score", 0))
    verdict = _get(report, "verdict", _get(report, "outcome"))
    if verdict is None:
        verdict = "PASS" if _get(report, "passed", False) else "CHANGES REQUESTED"
    policies: Sequence[object] = _get(report, "policies", ())
    findings: Sequence[object] = _get(report, "findings", ())
    analyzer_results: Sequence[object] = _get(report, "analyzer_results", ())
    considered = [result for result in analyzer_results if _get(result, "status") != "skipped"]
    completed = sum(_get(result, "status") == "completed" for result in considered)
    completeness = round(100 * completed / len(considered)) if considered else 100
    headline = f"**Quality score:** {score} / 100 &nbsp; **Verdict:** {_text(verdict)} &nbsp; "
    headline += f"**Analysis completeness:** {completeness}%"
    lines = [
        "## AgentGuard Change Quality Report",
        "",
        headline,
    ]
    if policies:
        lines.extend(
            ("", "### Quality gates", "", "| Policy | Result | Details |", "|---|---|---|")
        )
        for policy in policies:
            name = _get(policy, "name", _get(policy, "policy", "Policy"))
            details = _get(policy, "message", _get(policy, "reason", ""))
            lines.append(f"| {_text(name)} | {_status(policy)} | {_text(details)} |")

    important = list(findings[:max_findings])
    if important:
        lines.extend(
            (
                "",
                "### Actionable findings",
                "",
                "| Severity | Location | Finding |",
                "|---|---|---|",
            )
        )
        for finding in important:
            severity = _get(finding, "severity", "warning")
            path = _get(finding, "file", _get(finding, "path", ""))
            line = _get(finding, "line")
            location = f"`{_text(path)}{f':{line}' if line else ''}`" if path else "—"
            message = _get(finding, "message", "")
            remediation = _get(finding, "remediation")
            detail = f"{message} — {remediation}" if remediation else message
            lines.append(f"| {_text(severity)} | {location} | {_text(detail)} |")
    hidden = len(findings) - len(important)
    if hidden > 0:
        lines.extend(
            ("", f"_Showing {len(important)} findings; {hidden} additional findings omitted._")
        )
    lines.extend(("", "<sub>Generated by AgentGuard using deterministic analysis.</sub>"))
    return "\n".join(lines) + "\n"


class GitHubReporter:
    """Reporter interface used by the CLI."""

    def render(self, report: object) -> str:
        return render_github_markdown(report)
